# ====================================================          
presentation:
  template: "{0} - {1}<br/>
              {2} - {3}<br/>
              {4} - {5}<br/>
              "
  api: 
    template: "/estadicuf?categorias=cd_indicador_spai-cd_indicador,spai_ds,vl_indicador&filtros=eq-cd_uf-{0},and,in-cd_indicador_spai-'90_00_00_01'-'90_00_00_02'-'90_00_00_03'"
    args:
      - named_prop: "idLocalidade"
  args:
    - id: "90_00_00_02"
      named_prop: "spai_ds"
    - id: "90_00_00_02"
      named_prop: "vl_indicador"
    - id: "90_00_00_01"
      named_prop: "spai_ds"
    - id: "90_00_00_01"
      named_prop: "vl_indicador"
    - id: "90_00_00_03"
      named_prop: "spai_ds"
    - id: "90_00_00_03"
      named_prop: "vl_indicador"
