# <= 17         '< 18'
# <= 24         '18-24'
# <= 29         '25-29'
# <= 34         '30-34'
# <= 39         '35-39'
# <= 44         '40-44'
# <= 49         '45-49'
# <= 54         '50-54'
# <= 59         '55-59'
# > 59          '> 59'
bins: [0, 17, 24, 29, 34, 39, 44, 49, 54, 59, 200] # Valores extremos precisam ser incluídos para as pontas dos bins
right: true
labels:
  - '< 18'
  - '18-24'
  - '25-29'
  - '30-34'
  - '35-39'
  - '40-44'
  - '45-49'
  - '50-54'
  - '55-59'
  - '>= 60'