# ====================================================          
params:
  - name: "mapear"
    api:
      fixed: "/ti/mapear?categorias=nu_competencia_max&limit=1"
      options:
        calcs:
          - id: "nu_competencia_anterior"
            function: "calc_subtraction_ds"
            fn_args:
              - named_prop: "nu_competencia_max"
              - fixed: 2
