# ====================================================          
params:
  - name: "sst_beneficio"
    api:
      fixed: "/sst/beneficios?categorias=1&valor=ano_beneficio&agregacao=MIN,MAX"
  - name: "sst_cat"
    api:
      fixed: "/sst/cats?categorias=1&valor=ano_cat&agregacao=MIN,MAX"
