# ====================================================          
params:
  - name: "sst_beneficio"
    api:
      fixed: "/sst/indicadoresnacionais?categorias=nu_competencia_max&filtros=eq-cd_indicador-'sst_bene_qtd_91'&limit=1"
  - name: "sst_cat"
    api:
      fixed: "/sst/indicadoresnacionais?categorias=nu_competencia_max&filtros=eq-cd_indicador-'sst_cat_total'&limit=1"
