# ====================================================          
params:
  - name: "sst_beneficio"
    api:
      fixed: "/sst/beneficios?categorias=1&valor=ano_beneficio&agregacao=MIN,MAX"
      options:
        calcs:
          - id: "ano_beneficio_anterior"
            function: "calc_subtraction_ds"
            fn_args:
              - named_prop: "agr_max_ano_beneficio"
              - fixed: 1
  - name: "sst_cat"
    api:
      fixed: "/sst/cats?categorias=1&valor=ano_cat&agregacao=MIN,MAX"
      options:
        calcs:
          - id: "ano_cat_anterior"
            function: "calc_subtraction_ds"
            fn_args:
              - named_prop: "agr_max_ano_cat"
              - fixed: 1
