# ====================================================          
presentation:
  # template: "{0} - {1}<br/>
  #             {2} - {3}<br/>
  #             {4} - {5}<br/>
  #             {6} - {7}<br/>
  #             {8} - {9}<br/>
  #             {10} - {11}<br/>
  #             {12} - {13}<br/>
  #             "
  template: "{0} - {1}<br/>
              {2} - {3}<br/>
              {4} - {5}<br/>"
  api: 
    template: "/estadicmunic?categorias=cd_indicador_spai-cd_indicador,spai_ds,vl_indicador&filtros=eq-cd_mun_ibge-{0},and,in-cd_indicador_spai-'91_00_00_01'-'91_00_00_02'-'91_00_00_03'-'91_00_00_06'-'91_00_00_07'-'91_00_00_08'-'91_00_00_09'"
    args:
      - named_prop: "idLocalidade"
  args:
    - id: "91_00_00_03"
      named_prop: "spai_ds"
    - id: "91_00_00_03"
      named_prop: "vl_indicador"
    # - id: "91_00_00_06"
    #   named_prop: "spai_ds"
    # - id: "91_00_00_06"
    #   named_prop: "vl_indicador"
    # - id: "91_00_00_07"
    #   named_prop: "spai_ds"
    # - id: "91_00_00_07"
    #   named_prop: "vl_indicador"
    # - id: "91_00_00_08"
    #   named_prop: "spai_ds"
    # - id: "91_00_00_08"
    #   named_prop: "vl_indicador"
    # - id: "91_00_00_09"
    #   named_prop: "spai_ds"
    # - id: "91_00_00_09"
    #   named_prop: "vl_indicador"
    - id: "91_00_00_01"
      named_prop: "spai_ds"
    - id: "91_00_00_01"
      named_prop: "vl_indicador"
    - id: "91_00_00_02"
      named_prop: "spai_ds"
    - id: "91_00_00_02"
      named_prop: "vl_indicador"