# ====================================================          
master:
  template: '{0}&nbsp;habitantes (IBGE, {1})'
  preloaded:
    prop: "centralindicadores"
    function: "slice"
    id: "01_15_01_00"
    year: "max"
  args:
    - named_prop: "vl_indicador"
      format: 'inteiro'
      collapse:
        format: 'real'
        precision: 1
    - named_prop: "nu_competencia"
