# ====================================================          
master:
  template: '{0}&nbsp;habitantes ({1}, {2})'
  preloaded:
    prop: "centralindicadores"
    function: "slice"
    id: "01_17_01_00"
    year: "max"
  args:
    - named_prop: "vl_indicador"
      format: 'inteiro'
      collapse:
        format: 'real'
        precision: 1
    - named_prop: "ds_fonte"
    - function: "format_scope"
      fn_args:
        - named_prop: "nu_competencia"
        - fixed: "year"
