# ====================================================          
params:
  - name: "rais_agr"
    api:
      fixed: "/thematic/raisagrmun?categorias=1&agregacao=min,max&valor=rais_agr_ano_nu&filtros=le-rais_agr_ano_nu-2019"